version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - ./vol/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'fullstack'
      MYSQL_USER: 'splint'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
#    ports:
#      - 3306:3306
    expose:
      - 3306
    restart: always

  backend:
    build: ./backend
    image: backend
    container_name: backend
#    ports:
#      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_PUBLIC_URL: ${REACT_APP_PUBLIC_URL}
    image: frontend
    container_name: frontend
#    ports:
#      - 88:80
    expose:
      - 80
    restart: always

  nginx-proxy:
    image: nginx:1.23.3-alpine-slim
    container_name: nginx-proxy
    volumes:
      - ./vol/nginx/src:/usr/share/nginx/html
      - ./vol/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    expose:
      - 80
    restart: always

#volumes:
#  db:
